apiVersion: cornserve.ai/v1
kind: LatestTasklibRV
metadata:
  name: latest-tasklib-rv
  namespace: cornserve
spec:
  # Init with 0; gateway will update this value after each tasklib (re)deployment
  maxResourceVersion: 0

