apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: latesttasklibrvs.cornserve.ai
spec:
  group: cornserve.ai
  scope: Namespaced
  names:
    plural: latesttasklibrvs
    singular: latesttasklibrv
    kind: LatestTasklibRV
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                maxTaskClassRV:
                  type: integer
                maxDescriptorRV:
                  type: integer
              required: ["maxTaskClassRV", "maxDescriptorRV"]

