apiVersion: cornserve.ai/v1
kind: LatestTasklibRV
metadata:
  name: latest-tasklib-rv
  namespace: cornserve
spec:
  # Init with 0; gateway will update these values after each tasklib (re)deployment
  maxTaskClassRV: 0
  maxDescriptorRV: 0

