apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: unittaskprofiles.cornserve.ai
spec:
  group: cornserve.ai
  scope: Namespaced
  names:
    plural: unittaskprofiles
    singular: unittaskprofile
    kind: UnitTaskProfile
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                task:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                numGpusToProfile:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
              required: ["task", "numGpusToProfile"]
